server.port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/testDB
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        column_ordering_strategy: legacy

logging:
  level:
    org.hibernate.SQL: debug